#
# This workflow requires writing permissions to the repository.
# The GITHUB_TOKEN provided by the runner defaults to read-only permissions.
# Remember to add write permissions in `Settings -> Action -> General -> Workflow permissions`

name: Update GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.1'  # TODO: nix! reproducible builds! & a sprinkle of professionalism

    - name: Merge master into github_pages
      run: |
        git fetch origin
        git checkout github_pages
        git reset --hard origin/master

    - name: Install dependencies and build the web project
      working-directory: ./svelte_blinkenweb
      run: |
        npm ci
        npm run build

    - name: Remove old /docs content
      run: |
        rm -rf ./docs/*

    - name: Copy build to /docs
      run: |
        cp -r ./svelte_blinkenweb/dist/* ./docs/

    - name: Commit and push changes
      run: |
        # Note: the following account information will not work on GHES
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit -m "Update GitHub Pages with latest build from master"
        git push origin github_pages --force
